// BlueYard-inspired progressive disclosure; uses SPECTRA data and visual language.
const orbitLayout=document.getElementById('orbitLayout'),orbitNodes=document.getElementById('orbitNodes'),orbitSide=document.getElementById('orbitSide');let orbitStage='root',orbitCategory=null;
const orbit=document.querySelector('.orbit'),particleCanvas=document.createElement('canvas');particleCanvas.className='particle-field';particleCanvas.setAttribute('aria-hidden','true');orbit.prepend(particleCanvas);
const reduceMotion=true,particlePointer={x:.5,y:.5,active:false};let particles=[],particleFrame=0;
function sizeParticles(){const dpr=Math.min(devicePixelRatio||1,2),r=orbit.getBoundingClientRect();particleCanvas.width=r.width*dpr;particleCanvas.height=r.height*dpr;particleCanvas.style.width=r.width+'px';particleCanvas.style.height=r.height+'px';particles=Array.from({length:76},(_,i)=>({x:((i*73)%997)/997,y:((i*151)%991)/991,z:.35+((i*47)%100)/155,vx:(((i*31)%19)-9)*.000006,vy:(((i*17)%23)-11)*.000004,phase:i*.73}));drawParticles(0)}
function drawParticles(t=0){const dpr=Math.min(devicePixelRatio||1,2),r=orbit.getBoundingClientRect(),x=particleCanvas.getContext('2d'),ink=getComputedStyle(orbit).getPropertyValue('--blue').trim()||getComputedStyle(orbit).color;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);for(const p of particles){const px=p.x*r.width,py=p.y*r.height,near=p.z>.76;x.globalAlpha=.035+p.z*.3;x.fillStyle=ink;x.shadowColor=ink;x.shadowBlur=near?9:0;x.beginPath();x.arc(px,py,.28+p.z*1.5,0,Math.PI*2);x.fill()}x.shadowBlur=0;for(let i=0;i<9;i++){const px=((i*193+71)%941)/941*r.width,py=((i*131+87)%929)/929*r.height;x.globalAlpha=.035;x.fillStyle=ink;x.shadowColor=ink;x.shadowBlur=18;x.beginPath();x.arc(px,py,3+(i%3)*1.4,0,Math.PI*2);x.fill()}x.shadowBlur=0;x.globalAlpha=1}
orbit.addEventListener('pointermove',e=>{const r=orbit.getBoundingClientRect();particlePointer.x=(e.clientX-r.left)/r.width;particlePointer.y=(e.clientY-r.top)/r.height;particlePointer.active=true});orbit.addEventListener('pointerleave',()=>particlePointer.active=false);new ResizeObserver(sizeParticles).observe(orbit);sizeParticles();if(!reduceMotion)particleFrame=requestAnimationFrame(drawParticles);
const polar=(i,n,ring=1)=>{if(n===6&&orbitStage==='categories'){const a=-Math.PI/2+i*Math.PI/3;return {x:50+Math.cos(a)*32,y:49+Math.sin(a)*30}}const a=-Math.PI/2+i*Math.PI*2/n+.15,depth=(Math.sin(a)+1)/2,radius=ring===1?29:42;return{x:50+Math.cos(a)*radius*(.88+depth*.12),y:49+Math.sin(a)*(ring===1?30:42)+Math.cos(a)*5}};
function center(title,sub,action){document.getElementById('orbitTitle').textContent=title;document.getElementById('orbitHint').textContent=sub;document.querySelector('.orbit-center').dataset.action=action;orbit.dataset.stage=orbitStage;requestAnimationFrame(()=>{document.getElementById('orbitPage').textContent=orbitStage==='models'?'模型宇宙 / '+title:'模型宇宙 / 六个领域'});}
function enterNodes(){requestAnimationFrame(()=>requestAnimationFrame(()=>orbitNodes.querySelectorAll('.orbit-node').forEach(n=>{const depth=.72+(Number(n.dataset.y)/100)*.34;n.style.setProperty('--depth',depth.toFixed(2));n.style.left=n.dataset.x+'%';n.style.top=n.dataset.y+'%';n.classList.add('is-entered')})));}
function renderRoot(){orbitStage='root';orbitCategory=null;center('模型宇宙','点击进入','open');orbitNodes.innerHTML='';orbitSide.innerHTML='<span class="eyebrow">MODEL UNIVERSE</span><h3>从一个方向开始</h3><p>点击中心，逐层探索方向、公司与模型。页面不会一次铺开全部内容。</p>';document.getElementById('orbitPage').textContent='第 1 层 · 入口';}
function renderCategories(){orbitStage='categories';center('模型宇宙','六个领域','categories');orbitNodes.innerHTML=D.categories.map((c,i)=>{const p=polar(i,D.categories.length,1);return `<button class="orbit-node category" data-category="${c.id}" data-x="${p.x}" data-y="${p.y}" style="--delay:${i*45}ms"><span class="node-orb"></span><span class="node-copy"><strong>${esc(c.name)}</strong><small>${esc(c.hint)}</small></span></button>`}).join('');orbitSide.innerHTML='<span class="eyebrow">第 1 层 · 方向</span><h3>选择观察方向</h3><p>六个方向围绕中心展开。点击任一方向，其余方向收拢，再展开对应公司与模型。</p>';document.getElementById('orbitPage').textContent='第 1 层 · 6 个方向';enterNodes();}
function renderModels(id){orbitStage='models';orbitCategory=id;const c=category(id),models=D.models.filter(m=>m.category===id).sort((a,b)=>Number(isRecent(b))-Number(isRecent(a))||a.company.localeCompare(b.company,'zh-CN'));center(c.name,`${models.length} 个模型`,'categories');let inner=0,outer=0;const split=models.length>14?Math.ceil(models.length*.42):models.length;orbitNodes.innerHTML=models.map((m,i)=>{const ring=i>=split?2:1,slot=ring===1?inner++:outer++,count=ring===1?split:models.length-split,p=polar(slot,count,ring);return `<button class="orbit-node model ${isRecent(m)?'recent':''}" data-model="${m.id}" data-x="${p.x}" data-y="${p.y}" style="--delay:${Math.min(i*24,420)}ms"><span class="node-orb"></span>${isRecent(m)?'<i>更新</i>':''}<span class="node-copy"><small>${esc(m.company)}</small><strong>${esc(m.name)}</strong></span></button>`}).join('');orbitSide.innerHTML=`<span class="eyebrow">第 3 层 · ${models.length} 个条目</span><h3>${esc(c.name)}</h3><p>公司—模型名称沿环形展开。点击小节点进入模型档案；带“更新”的节点代表近 30 日存在明确发布记录。</p><button class="text-button" id="orbitBack">← 返回方向</button>`;document.getElementById('orbitBack').onclick=renderCategories;document.getElementById('orbitPage').textContent=`第 3 层 · ${models.length} / ${models.length}`;enterNodes();}
document.querySelector('.orbit-center').setAttribute('role','button');document.querySelector('.orbit-center').tabIndex=0;document.querySelector('.orbit-center').onclick=()=>{const a=document.querySelector('.orbit-center').dataset.action;if(a==='open'||a==='categories')renderCategories();else renderCategories()};document.querySelector('.orbit-center').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.click()}};
orbitNodes.onclick=e=>{const c=e.target.closest('[data-category]'),m=e.target.closest('[data-model]');if(c&&!orbitNodes.classList.contains('is-focusing')){orbitNodes.classList.add('is-focusing');c.classList.add('is-selected');setTimeout(()=>{orbitNodes.classList.remove('is-focusing');renderModels(c.dataset.category)},460)}if(m)showModel(m.dataset.model)};document.getElementById('orbitList').onclick=()=>openCategory(orbitCategory||'all');const catalogObserver=new MutationObserver(()=>{orbitLayout.hidden=!$('catalog').hidden;document.getElementById('orbitControls').hidden=!$('catalog').hidden});catalogObserver.observe($('catalog'),{attributes:true,attributeFilter:['hidden']});renderCategories();
