'use strict';
const D=window.PREVIEW_DATA,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external=(url,label)=>/^https:\/\//.test(url)?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
const category=id=>D.categories.find(c=>c.id===id);
const isRecent=m=>m.update&&m.update<=D.checkedAt&&m.update>=new Date(new Date(`${D.checkedAt}T00:00:00Z`).getTime()-29*86400000).toISOString().slice(0,10);
const OPEN_WEIGHT_IDS=new Set(['qwen-vl','qwen-coder','z-image','hy-video','cogview','cogvideox','qwen','deepseek','hunyuan','glm','minimax','qwen-image','wan','hunyuanworld','hy3d','genie','openwam','mimo','ling-model','baichuan','yi','llama','mistral','phi','nemotron','stable-diffusion','stable-video','cosmos','v-jepa']);
const API_IDS=new Set(['happyhorse','qwen-vl','qwen-coder','cogview','cogvideox','vidu','pangu','sensenova','spark','step','gpt','qwen','seed','deepseek','kimi','hunyuan','ernie','glm','minimax','claude','gemini','qwen-image','seedream','hy-image','gpt-image','wan','seedance','kling','veo','kimi-code','codex','mistral','grok','phi','amazon-nova','nemotron','stable-diffusion','flux','firefly','ideogram','recraft','sora','runway','luma-ray','pika','firefly-video','stable-video','cosmos','tripo','meshy','perplexity','amazon-q']);
const PRODUCT_IDS=new Set(['lingma','tingwu','dingtalk-ai','jimeng','trae','step-assistant','qwen-code','kling','hailuo','kimi-code','codebuddy','codex','claude-code','wps','ima','feishu','coze','kimi-work','workbuddy','minimax-agent','360-zhinao','midjourney','midjourney-video','sora','runway','luma-ray','pika','world-labs','odyssey','decart','tripo','meshy','copilot','cursor','windsurf','devin','copilot-work','gemini-workspace','notion-ai','perplexity','manus','amazon-q']);
function accessFor(m){if(m.access?.length)return m.access.join(' · ');const modes=[];if(OPEN_WEIGHT_IDS.has(m.id))modes.push('开放权重/可下载');if(API_IDS.has(m.id))modes.push('API');if(PRODUCT_IDS.has(m.id))modes.push('网页/App/桌面产品');if(/企业/.test(m.kind))modes.push('企业服务');if(/研究|世界模型/.test(m.kind)&&!API_IDS.has(m.id)&&!PRODUCT_IDS.has(m.id))modes.push('研究预览');return modes.length?[...new Set(modes)].join(' · '):'官方公开资料入口；具体开放方式待核实';}
function versionState(m){return `${m.currentVersion} · ${m.currentVersionStatus}`;}
let active='all',onlyFollow=false,opener=null,openerModel=null;
let followed=new Set();try{followed=new Set(JSON.parse(localStorage.getItem('spectra-ux-preview-follow')||'[]'));}catch{}
$('categories').innerHTML=D.categories.map(c=>`<button class="category" data-cat="${c.id}" aria-controls="catalog" aria-expanded="false"><span><strong>${c.name}${D.models.some(m=>m.category===c.id&&isRecent(m))?'<i class="new-dot" aria-label="含近期更新"></i>':''}</strong><small>${c.hint}</small></span><span class="arrow" aria-hidden="true">↗</span></button>`).join('');
function renderModels(){
 const q=$('search').value.trim().toLowerCase(),region=$('region').value;
 const models=D.models.filter(m=>(active==='all'||m.category===active)&&(!onlyFollow||followed.has(m.id))&&(region==='all'||(m.region||'cn')===region)&&(!$('recentOnly').checked||isRecent(m))&&[m.name,m.company,m.summary,m.kind,...m.versions.map(v=>v[0])].join(' ').toLowerCase().includes(q)).sort((a,b)=>Number(isRecent(b)||false)-Number(isRecent(a)||false)||Number(!!a.region)-Number(!!b.region)||(b.update||'').localeCompare(a.update||''));
 $('resultCount').textContent=`${models.length} 个条目`;
 $('modelList').innerHTML=models.length?models.map(m=>`<button class="model-row ${isRecent(m)?'recent':''}" data-model="${m.id}"><span><strong>${esc(m.name)}</strong><small>${esc(m.company)} · ${esc(m.kind)}</small></span><span class="model-desc">${esc(m.summary)}</span><span>${isRecent(m)?'<span class="badge blue">近期更新</span>':m.pending?'<span class="badge">待核实</span>':'↗'}</span></button>`).join(''):'<div class="empty">当前条件下没有收录条目。可清空搜索、切换范围，或取消“近 30 日更新”。<br><button class="text-button" id="reset">重置筛选 →</button></div>';
 $('reset')?.addEventListener('click',()=>{$('search').value='';$('region').value='all';$('recentOnly').checked=false;renderModels();});
}
function openCategory(id,follow=false){active=id;onlyFollow=follow;$('catalog').hidden=false;$('catalogTitle').textContent=follow?'我的关注':id==='all'?'全部模型与产品':category(id).name;$('search').value='';$('region').value='all';$('recentOnly').checked=false;$('categories').hidden=true;$('catalogTitle').focus({preventScroll:true});renderModels();}
function closeCatalog(){$('catalog').hidden=true;$('categories').hidden=false;document.querySelector(`[data-cat="${active}"]`)?.focus({preventScroll:true});}
$('categories').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b)openCategory(b.dataset.cat);});
$('allModels').onclick=()=>openCategory('all');$('myFollow').onclick=()=>{openCategory('all',true);$('catalog').scrollIntoView({block:'start'});};$('backCategories').onclick=closeCatalog;
['search','region','recentOnly'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderModels));
function showDialog(html,breadcrumb){if(!$('detail').open){opener=document.activeElement;openerModel=opener?.dataset?.model||null;}$('detailBreadcrumb').textContent=breadcrumb;$('detailContent').innerHTML=html;if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;$('detailContent').querySelector('button,a')?.focus({preventScroll:true});}
function showModel(id){const m=D.models.find(m=>m.id===id);if(!m)return;
 const links=D.news.filter(n=>(m.newsIds||[]).includes(n.id));
 showDialog(`<span class="badge">${esc(m.kind)}</span> ${isRecent(m)?'<span class="badge blue">近 30 日更新</span>':''}<h2 id="detailTitle">${esc(m.name)}</h2><p>${esc(m.summary)}</p><button class="follow" id="follow" aria-pressed="${followed.has(id)}">${followed.has(id)?'已关注 ✓':'＋ 关注此条目'}</button><dl><dt>所属机构</dt><dd>${esc(m.company)}</dd><dt>所属方向</dt><dd>${category(m.category).name}</dd><dt>当前版本</dt><dd>${esc(versionState(m))}</dd><dt>发布日期状态</dt><dd>${esc(m.releaseDate||m.releaseDateStatus)}</dd><dt>开放方式</dt><dd>${esc(accessFor(m))}</dd><dt>资料状态</dt><dd>${m.pending?'待继续核实':'已核对下方官方来源所载信息；不等于独立性能评测'}</dd><dt>核对日期</dt><dd>${esc(D.checkedAt)}（非发布日期）</dd></dl><h3>已确认版本与发布日期</h3><div class="versions">${m.versions.length?m.versions.map(v=>`<div class="version"><strong>${esc(v[0])}<small style="display:block">${esc(v[2]||"已确认版本摘录；状态待复核")} · ${external(v[3]||m.source,"版本来源")}</small></strong><span>${v[1]?v[1]:'官方发布日期未披露或待核实'}</span></div>`).join(''):`<p>${esc(m.releaseDateStatus)}；不猜测日期。</p>`}</div>${m.change?`<h3>这次更新了什么</h3><p>${esc(m.change)}</p>`:''}<h3>使用边界</h3><p>${esc(m.note||'上述简介概括官方定位，不表示其在所有任务中领先。开放方式、价格与授权应以具体版本的官方说明为准。')}</p><h3>相关资讯与来源</h3>${links.length?links.map(n=>`<p><button class="text-button" data-news="${n.id}">阅读本地分析 →</button></p>`).join(''):'<p>尚未关联本地新闻分析；可先阅读下方官方资料。</p>'}<p>${external(m.source,m.sourceLabel)}</p>${m.extraSource?`<p>${external(m.extraSource,'补充官方来源')}</p>`:''}<small>版本列表为已核实摘录；发布日期缺少官方证据时明确标记未披露或待核实，不以采集日代替。</small>`,`${category(m.category).name} / ${m.name}`);
 $('follow').onclick=()=>{if(followed.has(id))followed.delete(id);else followed.add(id);try{localStorage.setItem('spectra-ux-preview-follow',JSON.stringify([...followed]));}catch{}$('follow').textContent=followed.has(id)?'已关注 ✓':'＋ 关注此条目';$('follow').setAttribute('aria-pressed',String(followed.has(id)));if(!$('catalog').hidden)renderModels();};
}
$('modelList').addEventListener('click',e=>{const b=e.target.closest('[data-model]');if(b)showModel(b.dataset.model);});$('recentModel').onclick=()=>showModel('kimi-code');
$('detail').querySelector('.close').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close();}});$('detail').addEventListener('close',()=>opener?.isConnected&&opener.focus({preventScroll:true}));
function showNews(id){const n=D.news.find(n=>n.id===id);if(!n)return;showDialog(`<span class="badge">${esc(n.label)}</span><h2 id="detailTitle">${esc(n.title)}</h2><small>${n.date} · 历史快照条目</small><p>${esc(n.summary)}</p><h3>阅读边界</h3><p>${esc(n.provenance)}</p><p>${external(n.source,'阅读作者原文')}</p>${id==='openwam'?'<button class="text-button" data-open-model="openwam">查看 OpenWAM 档案 →</button>':''}`,'一周资讯 / 研究条目');}
document.addEventListener('click',e=>{const n=e.target.closest('[data-news]');if(n)showNews(n.dataset.news);const m=e.target.closest('[data-open-model]');if(m)showModel(m.dataset.openModel);});
const dates=['全部','09.04','09.05','09.06','09.07','09.08','09.09','09.10'];let day='全部';
function renderNews(){ $('days').innerHTML=dates.map(d=>`<button data-day="${d}" aria-pressed="${d===day}">${d}</button>`).join('');const rows=D.news.filter(n=>day==='全部'||n.date.slice(5).replace('-','.')===day);$('newsList').innerHTML=rows.length?rows.map(n=>`<article class="news-row"><span class="news-date">${n.date.slice(5).replace('-','.')}</span><div><small>${n.label}</small><h3><button data-news="${n.id}">${n.title}</button></h3><p>${n.summary}</p><button class="read" data-news="${n.id}">阅读线索 ↗</button></div></article>`).join(''):'<div class="empty" role="status">该日没有纳入本预览的研究条目，不代表当天没有新闻。<br><button class="text-button" id="allDays">查看整周 →</button></div>';$('allDays')?.addEventListener('click',()=>{day='全部';renderNews();});}
$('days').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b){day=b.dataset.day;renderNews();document.querySelector(`[data-day="${day}"]`).focus({preventScroll:true});}});renderNews();
$('ideas').onclick=()=>showDialog('<h2 id="detailTitle">视觉灵感库</h2><p>本次只制作总览单页，保留原平台的四个导航入口。灵感库原有功能不在本预览中重做。</p><p>可从世界与空间分类查看相关研究项目。</p><button class="text-button" id="goWorld">浏览世界与空间 →</button>','预览范围');
document.addEventListener('click',e=>{if(e.target.id==='goWorld'){$('detail').close();openCategory('world');}});
$('about').onclick=()=>showDialog(`<h2 id="detailTitle">数据与预览说明</h2><p>这是独立 HTML 交互预览，不改变正式网页，不触发采集、生图、审核或钉钉推送。</p><h3>模型目录</h3><p>当前收录 ${D.models.length} 个主要模型、产品与研究系列，覆盖国内外主要公开厂商。分类是浏览入口，不是互斥的技术定义；产品、模型系列、具体版本、研究框架分别标明。</p><p>“全市场”表示主要厂商覆盖，不表示世界上不存在遗漏。已确认版本不等于最新版本；没有可靠日期则显示待核实。资料核对基准日为 ${esc(D.checkedAt)}。</p><h3>核心资料</h3><p>优先补齐版本、官方发布日期与开放方式（开放权重、API、网页/App、企业服务、研究预览或未开放）。许可证和服务地区不作为全量完整度门槛，仅在影响实际使用判断时说明。</p><h3>一周资讯</h3><p>使用项目本地快照中的 3 条研究资讯演示日期筛选与阅读，不是整周采集总量。没有重新确认的实验数字不展示。</p><p>关注仅保存在本浏览器的独立预览存储中，不接入正式账号。</p>`,'预览说明');
// Navigation returns to the category overview rather than leaving an old list open.
document.querySelectorAll('.brand,nav a[aria-current]').forEach(a=>a.addEventListener('click',()=>{closeCatalog();window.scrollTo({top:0,behavior:'instant'});}));
$('detail').addEventListener('close',()=>{if(opener&&!opener.isConnected){const target=openerModel?document.querySelector(`[data-model="${openerModel}"]`):null;(target||$('catalogTitle')).focus({preventScroll:true});}});
